// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

namespace AIDownloader.Core.Models;

public class HuggingFaceModels
{
    public string _id { get; set; }
    public string modelId { get; set; }
    public string author { get; set; }
    public string sha { get; set; }
    public DateTimeOffset lastModified { get; set; }
    public bool disabled { get; set; }
    public string pipeline_tag { get; set; }
    public string[] tags { get; set; }
    public int downloads { get; set; }
    public string library_name { get; set; }
    public Widget[] widgetData { get; set; }
    public int likes { get; set; }
    public Config config { get; set; }
    public CardData cardData { get; set; }
    public TransformersInfo transformersInfo { get; set; }
    public string[] spaces { get; set; }
    public Sibling[] siblings { get; set; }
    public DateTime createdAt { get; set; }
    public Safetensors safetensors { get; set; }
}

public class Config
{
    public string[] architectures { get; set; }
    public string model_type { get; set; }
    public TokenizerConfig tokenizer_config { get; set; }
}

public class TokenizerConfig
{
    public string bos_token { get; set; }
    public string eos_token { get; set; }
    public string unk_token { get; set; }
    public bool use_default_system_prompt { get; set; }
    public string chat_template { get; set; }
}

public class CardData
{
    public string license { get; set; }
    public string pipeline_tag { get; set; }
    public string[] tags { get; set; }
    public bool inference { get; set; }
    public Widget[] widget { get; set; }
}

public class Widget
{
    public Message[] messages { get; set; }
}

public class Message
{
    public string role { get; set; }
    public string content { get; set; }
}

public class TransformersInfo
{
    public string auto_model { get; set; }
    public string pipeline_tag { get; set; }
    public string processor { get; set; }
}

public class Safetensors
{
    public Parameters parameters { get; set; }
    public long total { get; set; }
}

public class Parameters
{
    public long BF16 { get; set; }
}

public class Sibling
{
    public string rfilename { get; set; }
}

