// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

namespace AIDownloader.Core.Models;

public class ModelScopeResponse
{
    public int Code { get; set; }
    public ModelScopeData Data { get; set; }
    public string Message { get; set; }
    public string RequestId { get; set; }
    public bool Success { get; set; }
}

public class ModelScopeData
{
    public ModelScopeFile[] Files { get; set; }
    public int IsVisual { get; set; }
    public ModelScopeLatestcommitter LatestCommitter { get; set; }
}

public class ModelScopeLatestcommitter
{
    public string AuthorEmail { get; set; }
    public string AuthorName { get; set; }
    public int AuthoredDate { get; set; }
    public int CommittedDate { get; set; }
    public string CommitterEmail { get; set; }
    public string CommitterName { get; set; }
    public int CreatedAt { get; set; }
    public string Id { get; set; }
    public string Message { get; set; }
    public string[] ParentIds { get; set; }
    public string ShortId { get; set; }
    public string Title { get; set; }
}

public class ModelScopeFile
{
    public string CommitMessage { get; set; }
    public int CommittedDate { get; set; }
    public string CommitterName { get; set; }
    public bool InCheck { get; set; }
    public bool IsLFS { get; set; }
    public string Mode { get; set; }
    public string Name { get; set; }
    public string Path { get; set; }
    public string Revision { get; set; }
    public string Sha256 { get; set; }
    public long Size { get; set; }
    public string Type { get; set; }
}

