// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace RodelDownloader.Aria;

public class FileResult
{
    /// <summary>
    /// Completed length of this file in bytes. Please note that it is possible that sum of completedLength is less than
    /// the completedLength returned by the aria2.tellStatus() method. This is because completedLength in aria2.getFiles()
    /// only includes completed pieces. On the other hand, completedLength in aria2.tellStatus() also includes partially
    /// completed pieces.
    /// </summary>
    [JsonPropertyName("completedLength")]
    public string CompletedLength { get; set; }

    /// <summary>
    /// Index of the file, starting at 1, in the same order as files appear in the multi-file torrent.
    /// </summary>
    [JsonPropertyName("index")]
    public string Index { get; set; }

    /// <summary>
    /// File size in bytes.
    /// </summary>
    [JsonPropertyName("length")]
    public string Length { get; set; }

    /// <summary>
    /// File path.
    /// </summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = null!;

    /// <summary>
    /// true if this file is selected by --select-file option. If --select-file is not specified or this is single-file
    /// torrent or not a torrent download at all, this value is always true. Otherwise false.
    /// </summary>
    [JsonPropertyName("selected")]
    public string Selected { get; set; }

    /// <summary>
    /// Returns a list of URIs for this file. The element type is the same struct used in the aria2.getUris() method.
    /// </summary>
    [JsonPropertyName("uris")]
    public List<UriResult> Uris { get; set; } = new List<UriResult>();
}
