// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace AIDownloader.Aria;

public class GlobalStatResult
{
    [JsonPropertyName("downloadSpeed")]
    public decimal DownloadSpeed { get; set; }

    [JsonPropertyName("numActive")]
    public int NumActive { get; set; }

    [JsonPropertyName("numStopped")]
    public int NumStopped { get; set; }

    [JsonPropertyName("numStoppedTotal")]
    public int NumStoppedTotal { get; set; }

    [JsonPropertyName("numWaiting")]
    public int NumWaiting { get; set; }

    [JsonPropertyName("uploadSpeed")]
    public decimal UploadSpeed { get; set; }
}
