// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace AIDownloader.Aria;

public class GlobalStatResult
{
    [JsonPropertyName("downloadSpeed")]
    public decimal DownloadSpeed { get; set; }

    [JsonPropertyName("numActive")]
    public string NumActive { get; set; }

    [JsonPropertyName("numStopped")]
    public string NumStopped { get; set; }

    [JsonPropertyName("numStoppedTotal")]
    public string NumStoppedTotal { get; set; }

    [JsonPropertyName("numWaiting")]
    public string NumWaiting { get; set; }

    [JsonPropertyName("uploadSpeed")]
    public decimal UploadSpeed { get; set; }
}
