// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace AIDownloader.Aria;

public class ServerResult
{
    [JsonPropertyName("index")]
    public string Index { get; set; } = null!;

    [JsonPropertyName("servers")]
    public List<ServerResultServer> Servers { get; set; } = new List<ServerResultServer>();
}

public class ServerResultServer
{
    [JsonPropertyName("currentUri")]
    public string CurrentUri { get; set; } = null!;

    [JsonPropertyName("downloadSpeed")]
    public string DownloadSpeed { get; set; }

    [JsonPropertyName("uri")]
    public string Uri { get; set; } = null!;
}
