// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace AIDownloader.Aria;

public class SessionResult
{
    [JsonPropertyName("sessionId")]
    public string SessionId { get; set; } = null!;
}
