// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace AIDownloader.Aria;

public class UriResult
{
    /// <summary>
    /// 'used' if the URI is in use. 'waiting' if the URI is still waiting in the queue.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = null!;

    /// <summary>
    /// URI
    /// </summary>
    [JsonPropertyName("uri")]
    public string Uri { get; set; } = null!;
}
