// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace AIDownloader.Aria;

public class VersionResult
{
    /// <summary>
    /// List of enabled features. Each feature is given as a string.
    /// </summary>
    [JsonPropertyName("enabledFeatures")]
    public List<string> EnabledFeatures { get; set; } = new List<string>();

    /// <summary>
    /// Version number of aria2 as a string.
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; set; } = null!;
}
