// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using Markdig.Syntax;
using AIDownloader.UI.Controls.Markdown.TextElements;

namespace AIDownloader.UI.Controls.Markdown.Renderers.ObjectRenderers;

internal class CodeBlockRenderer : WinUIObjectRenderer<CodeBlock>
{
    protected override void Write(WinUIRenderer renderer, CodeBlock obj)
    {
        var code = new MyCodeBlock(obj, renderer.Config);
        renderer.Push(code);
        renderer.Pop();
    }
}
