// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using Markdig.Syntax;
using AIDownloader.UI.Controls.Markdown.TextElements;

namespace AIDownloader.UI.Controls.Markdown.Renderers.ObjectRenderers;

internal class ParagraphRenderer : WinUIObjectRenderer<ParagraphBlock>
{
    protected override void Write(WinUIRenderer renderer, ParagraphBlock obj)
    {
        if (renderer == null)
        {
            throw new ArgumentNullException(nameof(renderer));
        }

        if (obj == null)
        {
            throw new ArgumentNullException(nameof(obj));
        }

        var paragraph = new MyParagraph(obj);

        // set style
        renderer.Push(paragraph);
        renderer.WriteLeafInline(obj);
        renderer.Pop();
    }
}
