// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using Markdig.Renderers;
using Markdig.Syntax;

namespace AIDownloader.UI.Controls.Markdown.Renderers;

public abstract class WinUIObjectRenderer<TObject> : MarkdownObjectRenderer<WinUIRenderer, TObject>
where TObject : MarkdownObject
{
}
