// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

namespace AIDownloader.UI.Controls.Markdown;

public interface IImageProvider
{
    Task<Image> GetImage(string url);
    bool ShouldUseThisProvider(string url);
}
