// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

namespace AIDownloader.UI.Controls.Markdown;

public interface ISVGRenderer
{
    Task<Image> SvgToImage(string svgString);
}
