// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

namespace AIDownloader.UI.Controls.Markdown;

public record MarkdownConfig
{
    public string BaseUrl { get; set; }
    public IImageProvider ImageProvider { get; set; }
    public ISVGRenderer SVGRenderer { get; set; }
    public MarkdownThemes Themes { get; set; } = MarkdownThemes.Default;

    public static MarkdownConfig Default = new();
}
