// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

using Microsoft.UI.Xaml.Documents;

namespace AI.Downloader.UI.Controls.Markdown.TextElements;

public interface IAddChild
{
    TextElement TextElement { get; }
    void AddChild(IAddChild child);
}
