// Copyright (c) AI Downloader. All rights reserved.
// <auto-generated />

namespace RodelDownloader.UI.Models.Constants;

/// <summary>
/// 设置名称.
/// </summary>
public enum SettingNames
{
    AppTheme,
    LastWindowWidth,
    LastWindowHeight,
    IsWindowMaximized,

    CivitaiToken,
    CivitaiSaveFolders,
    CivitaiLastSaveFolder,
    CivitaiLastModelId,
    HuggingFaceToken,
    HuggingFaceUriType,
    HuggingFaceSaveFolders,
    HuggingFaceLastSaveFolder,
    HuggingFaceLastModelId,
    ModelScopeToken,
    ModelScopeSaveFolders,
    ModelScopeLastSaveFolder,
    ModelScopeLastModelId,

    SkipWelcome,
    LastDonwloadType,
}
